create table if not exists boards (
	id int generated by default as identity primary key,
	name text not null,
	user_id int not null references users(id) on delete cascade on update cascade,
	created_at timestamptz default now()
);
