create table if not exists users(
	id int generated by default as identity primary key,
	name text not null,
	email_address text unique not null,
	password text not null,
	created_at timestamptz default now()
);
