create table if not exists users(
	id int generated by default as identity primary key,
	name text not null,
	email_address text unique not null,
	password text not null,
	created_at timestamptz default now()
);
create table if not exists boards (
	id int generated by default as identity primary key,
	name text not null,
	user_id int not null references users(id) on delete cascade on update cascade,
	created_at timestamptz default now()
);
create table if not exists lists (
	id int generated by default as identity primary key,
	name text not null,
	board_id int not null references boards(id) on delete cascade on update cascade,
	user_id int not null references users(id) on delete cascade on update cascade,
	created_at timestamptz default now()
);
create table if not exists cards (
	id int generated by default as identity primary key,
	body text not null,
	list_id int not null references lists(id) on delete cascade on update cascade,
	user_id int not null references users(id) on delete cascade on update cascade,
	created_at timestamptz default now(),
	position int not null
);
