create table boards (
	board_id int generated by default as identity primary key,
	name text not null,
	owner_id int not null references users(user_id) on delete cascade on update cascade,
	created_at timestamptz default now()
);
