-- DDL generated by Postico 1.5.5
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE "Cards" (
    id integer DEFAULT nextval('"Cards_id_seq"'::regclass) PRIMARY KEY,
    name character varying(100) NOT NULL,
    list integer NOT NULL REFERENCES "Lists"(id) ON DELETE CASCADE ON UPDATE CASCADE,
    description text,
    "createdAt" timestamp without time zone DEFAULT now(),
    position integer NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX "Cards_pkey" ON "Cards"(id int4_ops);

