create table lists (
	id int generated by default as identity primary key,
	name text not null,
	board_id int not null references boards(id) on delete cascade on update cascade,
	user_id int not null references users(id) on delete cascade on update cascade,
	created_at timestamptz default now()
);
