create table lists (
	list_id int generated by default as identity primary key,
	name text not null,
	board_id int not null references boards(board_id) on delete cascade on update cascade,
	owner_id int not null references users(user_id) on delete cascade on update cascade,
	created_at timestamptz default now()
);
