-- DDL generated by Postico 1.5.5
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE "Lists" (
    id integer DEFAULT nextval('"Lists_id_seq"'::regclass) PRIMARY KEY,
    name character varying(200) NOT NULL,
    board integer NOT NULL REFERENCES "Boards"(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    "createdAt" timestamp without time zone DEFAULT now()
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX "Lists_pkey" ON "Lists"(id int4_ops);

