create table users(
	user_id int generated by default as identity primary key,
	name text not null,
	email_address text unique not null,
	password text not null,
	salt text not null,
	created_at timestamptz default now()
);
